name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Secret
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "Dein API Key ist sicher gespeichert."
